name: Generate Test Reports on PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          touch .env
          echo

      - name: Run tests
        run: npx allure:run
        continue-on-error: true
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL}}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD}}
          USER_PHONE: ${{ secrets.USER_PHONE}}
          USER_EMAIL_MAIL_REG: ${{  secrets.USER_EMAIL_MAIL_REG }}
          USER_PASSWORD_MAIL_REG: ${{ secrets.USER_PASSWORD_MAIL_REG }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./allure-report
